### ISSUE TITLE
Error when destination function's prototype set to undefined

### ISSUE THREAD

**Issue by meeber** [bendrucker/fill-keys#1]
Hello good sir! I'm running into an issue when a destination function's `prototype` property is explicitly set to `undefined` (as opposed to not being defined at all) while a source function's `prototype` is defined.

Stripped down example:

``` js
const fillKeys = require("fill-keys");

const src = function () {};

const dst1 = () => {};
fillKeys(dst1, src); // Worky

const dst2 = () => {};
dst2.prototype = undefined;
fillKeys(dst2, src); // No Worky
```

> TypeError: argument dest is required
>     at merge (/opt/code/murr/node_modules/merge-descriptors/index.js:36:11)
>     at fill (/opt/code/murr/node_modules/fill-keys/index.js:11:7)
>     at fillKeys (/opt/code/murr/node_modules/fill-keys/index.js:18:10)
>     at Object.<anonymous> (/opt/code/murr/murr.js:11:1)
>     at Module._compile (module.js:541:32)
>     at Object.Module._extensions..js (module.js:550:10)
>     at Module.load (module.js:458:32)
>     at tryModuleLoad (module.js:417:12)
>     at Function.Module._load (module.js:409:3)
>     at Module.runMain (module.js:575:10)

This occurs because `merge-descriptors` doesn't overwrite `dst2`'s explicitly set `prototype` value of `undefined` with `src`'s `prototype` since `redefine` is set to `false` when calling `merge` the first time [here](https://github.com/bendrucker/fill-keys/blob/b2a12c4bbbcc1dfea2a9603ba8d1ea979503dbb1/index.js#L9).

(By the way, an "in the wild" example of this issue is creating a sinon spy of an arrow function and then using it as a proxyquire substitution. I'm not convinced sinon is doing the optimal thing by returning a spy with `prototype` explicitly set to `undefined`, but I figured it's best to submit the issue here first since it can be reproduced without sinon.)

**Comment by bendrucker** [comment]
Sounds reasonable, would appreciate a PR if you have time but otherwise I can take care of this

**Comment by meeber** [comment]
Just to be sure, is the desired behavior in this situation to simply not call the [second merge](https://github.com/bendrucker/fill-keys/blob/b2a12c4bbbcc1dfea2a9603ba8d1ea979503dbb1/index.js#L11)? If so, I can cook up a PR with relevant test.

However, if the desired behavior is instead for `dst2`'s `prototype` property to be set to `src`'s `prototype` property during the first call to `merge`, thus treating a property the same regardless if it's explicitly set to `undefined` or if it's just not defined, then I'd want to talk about it a little more before submitting anything.

**Comment by bendrucker** [comment]
Hmm, I think the latter is more consistents (setting the destination's prototype to a copy of the source's prototype). Any reason you can think of not to do that?

**Comment by meeber** [comment]
I think this is just one of those javascript things that you could make an argument either way and still be right. 

My preference is also the latter option. I feel that "not defined" and "set to undefined" should be treated the same for all properties (not just `prototype`), and that it's more appropriate in general to explicitly set a property to `null` instead of `undefined`. 

Unfortunately, that approach means either requesting a change to how `merge-descriptors` handles `undefined` properties when `redefine` is false, or forking the project, or baking the modified `merge` logic straight into `fill-keys`.

**Comment by bendrucker** [comment]
I'm okay with the logic living in fill-keys

**Comment by meeber** [comment]
I'll whip up a PR then!
